// GENERATED by apps/site/scripts/gen-counts.mjs — do not edit.
//
// Every number the marketing site shows a visitor lives here and is derived from
// the repo, because the hand-typed versions went stale and contradicted each other
// on the front page. Run `node apps/site/scripts/gen-counts.mjs` to regenerate;
// `pnpm verify` fails if this file and the repo disagree.

/** Documented component pages — one per entry in `DEMO_META`. */
export const COMPONENT_COUNT = 116;

/** Registered vanilla behaviors — the `HANDLERS` table in silicaui-behaviors. */
export const BEHAVIOR_COUNT = 35;

/** Published packages — `packages/*` excluding anything marked private. */
export const PACKAGE_COUNT = 12;

/** The published package names, in case a page wants to list rather than count. */
export const PACKAGE_NAMES = [
  "@wizeworks/silicaui",
  "@wizeworks/silicaui-behaviors",
  "@wizeworks/silicaui-builder",
  "@wizeworks/silicaui-charts",
  "@wizeworks/silicaui-dnd",
  "@wizeworks/silicaui-editor",
  "@wizeworks/silicaui-fonts",
  "@wizeworks/silicaui-html",
  "@wizeworks/silicaui-mcp",
  "@wizeworks/silicaui-panels",
  "@wizeworks/silicaui-react",
  "@wizeworks/silicaui-table",
] as const;
