// Bakes the exact Lucide icons the builder uses into src/icons.ts as inline SVG
// inner-markup — so the builder renders real icons with NO runtime dependency
// (lucide-static is only the dev-time source of truth). Re-run after editing the
// USED map. Source: Lucide (ISC/MIT). Run: node scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const HERE = dirname(fileURLToPath(import.meta.url));
const ICONS = join(dirname(require.resolve("lucide-static/package.json")), "icons");

// Every icon the builder references, by our semantic name → Lucide file.
const USED = {
  // node types
  heading: "heading", text: "type", button: "square-mouse-pointer", image: "image",
  link: "link", section: "layout-template", grid: "layout-grid", stack: "rows-3",
  box: "box", list: "list", item: "dot", form: "text-cursor-input", input: "text-cursor-input",
  label: "tag", nav: "menu", header: "panel-top", footer: "panel-bottom", main: "square",
  article: "file-text", aside: "panel-right", outlet: "square-dashed",
  // chrome / ui
  lock: "lock", shared: "link-2", undo: "undo-2", redo: "redo-2", command: "command",
  plus: "plus", chevron: "chevron-right", close: "x", sun: "sun", moon: "moon",
  monitor: "monitor", tablet: "tablet", smartphone: "smartphone",
  page: "file", layout: "panels-top-left", theme: "palette", dot: "circle",
  // theme editor
  shuffle: "shuffle", sliders: "sliders-horizontal", download: "download",
  check: "check", droplet: "droplet",
};

// Pull the inner markup out of each <svg>…</svg> (Lucide files share one root svg).
const inner = (name) => {
  const svg = readFileSync(join(ICONS, `${name}.svg`), "utf8");
  const m = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!m) throw new Error(`no svg body in ${name}`);
  return m[1].replace(/\s+/g, " ").trim();
};

const entries = Object.entries(USED)
  .map(([key, file]) => `  ${key}: ${JSON.stringify(inner(file))},`)
  .join("\n");

const out = `/**
 * Lucide icons the builder uses, baked to inline SVG inner-markup (Lucide, ISC).
 * GENERATED by scripts/gen-icons.mjs — do not edit by hand; add a name to that
 * script's USED map and re-run. Rendered as inline SVG so there is no icon font,
 * no CDN, and nothing to fetch (CSP-safe). silicaui core stays icon-agnostic;
 * this concrete set lives with the builder.
 */
export type IconName = keyof typeof ICON_BODY;

const ICON_BODY = {
${entries}
} as const;

/**
 * Inline SVG for \`name\`, sized in em so it scales with font-size and inherits
 * \`currentColor\`. Size it by setting font-size (or a Tailwind text-* / [&>svg]
 * utility) on an ancestor; inside silicaui components (\`.btn\` etc.) their own
 * \`svg\` rule sizes it automatically.
 */
export function icon(name: IconName): string {
  return (
    \`<svg viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" \` +
    \`stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">\${ICON_BODY[name]}</svg>\`
  );
}

/** A node type-label (Heading, Grid, …) → the icon that represents it. */
export function typeIcon(typeLabelText: string): IconName {
  const key = typeLabelText.toLowerCase();
  return (key in ICON_BODY ? (key as IconName) : "box");
}
`;

writeFileSync(join(HERE, "..", "src", "icons.ts"), out);
console.log(`icons.ts generated — ${Object.keys(USED).length} icons`);
