/** Plain id/title pairs, generated 1:1 from registry.tsx DEMOS — kept in its own
 * hook-free module (no component imports at all) so a Server Component (e.g.
 * generateStaticParams) can read it safely. The actual Demo components stay
 * in the main entry, which is client-only. */
export interface DemoMeta {
  id: string;
  title: string;
}

export const DEMO_META: DemoMeta[] = [
  { id: "typography", title: "Typography" },
  { id: "button", title: "Button" },
  { id: "badge", title: "Badge" },
  { id: "input", title: "Input" },
  { id: "input-group", title: "Input Group" },
  { id: "password-input", title: "Password Input" },
  { id: "search-input", title: "Search Input" },
  { id: "pin-input", title: "Pin Input" },
  { id: "phone-input", title: "Phone Input" },
  { id: "select", title: "Select (Native)" },
  { id: "textarea", title: "Textarea" },
  { id: "card", title: "Card" },
  { id: "alert", title: "Alert" },
  { id: "progress", title: "Progress" },
  { id: "avatar", title: "Avatar" },
  { id: "skeleton", title: "Skeleton" },
  { id: "table", title: "Table" },
  { id: "divider", title: "Divider" },
  { id: "kbd", title: "Kbd" },
  { id: "timestamp", title: "Timestamp" },
  { id: "breadcrumb", title: "Breadcrumb" },
  { id: "stat", title: "Stat" },
  { id: "steps", title: "Steps" },
  { id: "join", title: "Join" },
  { id: "menu", title: "Menu" },
  { id: "collapse", title: "Collapse" },
  { id: "indicator", title: "Indicator" },
  { id: "loading", title: "Loading" },
  { id: "prose", title: "Prose" },
  { id: "navbar", title: "Navbar" },
  { id: "footer", title: "Footer" },
  { id: "hero", title: "Hero" },
  { id: "link", title: "Link" },
  { id: "mockup", title: "Mockup" },
  { id: "timeline", title: "Timeline" },
  { id: "carousel", title: "Carousel" },
  { id: "stack", title: "Stack" },
  { id: "rating", title: "Rating" },
  { id: "radial-progress", title: "Radial Progress" },
  { id: "pagination", title: "Pagination" },
  { id: "accordion", title: "Accordion" },
  { id: "chat", title: "Chat" },
  { id: "range", title: "Range" },
  { id: "toast", title: "Toast" },
  { id: "swap", title: "Swap" },
  { id: "status", title: "Status" },
  { id: "countdown", title: "Countdown" },
  { id: "number-field", title: "Number Field" },
  { id: "drawer", title: "Drawer" },
  { id: "list", title: "List" },
  { id: "file-input", title: "File Input" },
  { id: "dock", title: "Dock" },
  { id: "fieldset", title: "Fieldset" },
  { id: "label", title: "Label" },
  { id: "validator", title: "Validator" },
  { id: "diff", title: "Diff" },
  { id: "mask", title: "Mask" },
  { id: "meter", title: "Meter" },
  { id: "scroll-area", title: "Scroll Area" },
  { id: "preview-card", title: "Preview Card" },
  { id: "toolbar", title: "Toolbar" },
  { id: "navigation-menu", title: "Navigation Menu" },
  { id: "menubar", title: "Menubar" },
  { id: "toggle-group", title: "Toggle Group" },
  { id: "field", title: "Field" },
  { id: "radio-group", title: "Radio Group" },
  { id: "checkbox-group", title: "Checkbox Group" },
  { id: "slider", title: "Slider" },
  { id: "switch", title: "Switch" },
  { id: "collapsible", title: "Collapsible" },
  { id: "filter", title: "Filter" },
  { id: "select-menu", title: "Select (Advanced)" },
  { id: "combobox", title: "Combobox" },
  { id: "multi-select", title: "Multi Select" },
  { id: "outline", title: "Outline" },
  { id: "date-input", title: "Date Input" },
  { id: "time-input", title: "Time Input" },
  { id: "date-time-input", title: "Date Time Input" },
  { id: "lightbox", title: "Lightbox" },
  { id: "overlay", title: "Overlay" },
  { id: "overflow-list", title: "Overflow List" },
  { id: "metadata-list", title: "Metadata List" },
  { id: "chat-suite", title: "Chat Suite" },
  { id: "power-search", title: "Power Search" },
  { id: "app-shell", title: "App Shell" },
  { id: "hooks", title: "Hooks" },
  { id: "calendar", title: "Calendar" },
  { id: "data-table", title: "Data Table" },
  { id: "empty-state", title: "Empty State" },
  { id: "tag-input", title: "Tag Input" },
  { id: "chart", title: "Chart" },
  { id: "color-picker", title: "Color Picker" },
  { id: "command-palette", title: "Command Palette" },
  { id: "tree-view", title: "Tree View" },
  { id: "dropzone", title: "Dropzone" },
  { id: "file-upload", title: "File Upload" },
  { id: "wizard", title: "Wizard" },
  { id: "rich-text-editor", title: "Rich Text Editor" },
  { id: "sortable-list", title: "Sortable List" },
  { id: "resizable-panels", title: "Resizable Panels" },
  { id: "tooltip", title: "Tooltip" },
  { id: "dialog", title: "Dialog" },
  { id: "alert-dialog", title: "Alert Dialog" },
  { id: "popover", title: "Popover" },
  { id: "dropdown", title: "Dropdown" },
  { id: "tabs", title: "Tabs" },
  { id: "checkbox", title: "Checkbox" },
  { id: "radio", title: "Radio" },
  { id: "toggle", title: "Toggle" },
  { id: "wordmark", title: "Wordmark" },
  { id: "selection-list", title: "Selection List" },
  { id: "sidebar", title: "Sidebar" },
  { id: "animations", title: "Animations" },
];
